[package]
name = "shell"
version = "1.0.0"
edition = "2024_07"
cairo-version = "2.12.3+nightly-2025-10-03"
description = "An oracle that executes shell commands on the local machine"
authors = ["Software Mansion <contact@swmansion.com>"]
license = "MIT"
repository = "https://github.com/software-mansion/cairo-oracle"
documentation = "https://docs.swmansion.com/cairo-oracle/shell/"

[dependencies]
oracle = { version = "1.0.0", path = "../oracle" }

[dev-dependencies]
cairo_test = "2"
