[package]
name = "shell"
version = "0.1.0-dev.0"
edition = "2024_07"
cairo-version = "2.12.3+dev-2025-09-23"
description = "An oracle that executes shell commands on the local machine"
authors = ["Software Mansion <contact@swmansion.com>"]
license = "MIT"
repository = "https://github.com/software-mansion/cairo-oracle"
documentation = "https://docs.swmansion.com/cairo-oracle"

[dependencies]
oracle = { version = "0.1.0-dev.4", path = "../oracle" }

[dev-dependencies]
cairo_test = "2"
