[package]
name = "example"
version = "0.1.0"
edition = "2024_07"
publish = false
assets = ["example-oracle/target/wasm32-wasip2/release/example_oracle.wasm"]

[executable]

[dependencies]
cairo_execute = "2"
oracle = { path = ".." }

[dev-dependencies]
cairo_test = "2"

[scripts]
build = "cargo build --manifest-path example-oracle/Cargo.toml --release --target wasm32-wasip2"
