[package]
name = "example"
version = "0.1.0"
edition = "2024_07"
publish = false

[executable]

[cairo]
enable-gas = false

[dependencies]
cairo_execute = "2.11.4"
oracle = { path = ".." }

[dev-dependencies]
cairo_test = "2.11.4"
