[package]
name = "example"
version = "0.1.0"
edition = "2024_07"
publish = false
assets = ["example-oracle/target/wasm32-wasip2/release/mypkg-oracle.wasm"]

[executable]

[dependencies]
cairo_execute = "2"
oracle = { path = ".." }

[dev-dependencies]
cairo_test = "2"
