[package]
name = "oracle"
version = "0.1.0-dev.3"
edition = "2024_07"
cairo-version = "2.12.0-rc.2"
description = "Interfaces for calling external oracles"
authors = ["Software Mansion <contact@swmansion.com>"]
homepage = "https://docs.swmansion.com/scarb"
license = "MIT"
repository = "https://github.com/software-mansion/cairo-oracle"
documentation = "https://docs.swmansion.com/cairo-oracle"

[dependencies]

[dev-dependencies]
cairo_test = "2"
