name: CI
on:
  push:
    branches: [main]
  merge_group:
  pull_request:
jobs:
  check-cairo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: software-mansion/setup-scarb@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip2
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: example/example-oracle
      - run: scarb fmt --check
      - run: scarb lint
      - run: scarb test --experimental-oracles

  check-rust:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "${{ env.CARGO_MANIFEST_DIR }}"
      - run: cargo fmt --manifest-path example/example-oracle/Cargo.toml --check
      - run: cargo clippy --manifest-path example/example-oracle/Cargo.toml --all-targets --all-features --no-deps
        env:
          RUSTFLAGS: "-Dwarnings"

  check-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
      - uses: software-mansion/setup-scarb@v1
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip2
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: example/example-oracle
      - run: bin/check-example
