name: CI
on:
  push:
    branches: [main]
  merge_group:
  pull_request:
jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
      - run: scarb fmt --check
      - run: scarb lint
      - run: scarb test
