name: CI
on:
  push:
    branches: [main]
  merge_group:
  pull_request:
jobs:
  check-cairo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
      - run: scarb fmt --check
      - run: scarb lint
      - run: scarb test

  check-rust:
    runs-on: ubuntu-latest
    env:
      CARGO_MANIFEST_DIR: example/example-oracle
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          components: rustfmt, clippy
      - uses: Swatinem/rust-cache@v2
        with:
          workspaces: "${{ env.CARGO_MANIFEST_DIR }}"
      - run: cargo fmt --check
      - run: cargo clippy --all-targets --all-features--no-deps
        env:
          RUSTFLAGS: "-Dwarnings"
      - run: cargo doc --all-features--no-deps
        env:
          RUSTDOCFLAGS: "-Dwarnings"
      - run: cargo test

  check-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: asdf-vm/actions/install@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-wasip2
      - uses: Swatinem/rust-cache@v2
      - run: bin/check-example
