name: Docs

on:
  push:
    tags:
      - 'oracle/*'
      - 'shell/*'
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: software-mansion/setup-scarb@v1
      - name: Build oracle docs
        run: scarb doc -p oracle --build
      - name: Build shell docs
        run: scarb doc -p shell --build
      - name: Prepare docs directory structure
        run: |
          mkdir -p _site/oracle _site/shell
          cp -r target/doc/oracle/book/* _site/oracle/
          cp -r target/doc/shell/book/* _site/shell/
          # Create a redirect at the root for backward compatibility
          cat > _site/index.html << 'EOF'
          <!DOCTYPE html>
          <html>
          <head>
            <meta http-equiv="refresh" content="0; url=/cairo-oracle/oracle/" />
            <title>Redirecting to Oracle docs</title>
          </head>
          <body>
            <p>Redirecting to <a href="/cairo-oracle/oracle/">Oracle documentation</a>...</p>
          </body>
          </html>
          EOF
      - uses: actions/configure-pages@v5
      - uses: actions/upload-pages-artifact@v3
        with:
          path: _site

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
